name = "atomic-swap/on-chain"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "On-chain validators for atomic-swap"

[repository]
user = "atomic-swap"
project = "on-chain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
