# atomic-swap — Cardano protocol project
# Generated by cardano-init. Edit freely.
#
# The top level aggregates the tasks that terminate and compose: build, test,
# clean. Long-running / interactive tasks (watch modes, local devnets, REPLs)
# are per-component and optional — a component exposes `dev` only when it has
# such a mode. Run one directly, e.g. `just -f <dir>/Justfile dev`; list a
# component's targets with `just -f <dir>/Justfile --list`. See README.md.

default:
    @just --list

# --- On-chain (Aiken) ---
build-on-chain:
    just -f on-chain/Justfile build

test-on-chain:
    just -f on-chain/Justfile test

# --- Off-chain (MeshJS) ---
build-off-chain:
    just -f off-chain/Justfile build

test-off-chain:
    just -f off-chain/Justfile test

# --- Aggregate tasks ---
build: build-on-chain build-off-chain
    @echo '{{BOLD + GREEN}}✓ Build complete{{NORMAL}}'

# Build the on-chain blueprint first (consumers read ../blueprint/plutus.json),
# then run each component's tests in role order.
test: build-on-chain test-on-chain test-off-chain
    @echo '{{BOLD + BLACK + BG_GREEN}}  ✓  All tests passed  {{NORMAL}}'

clean:
    just -f on-chain/Justfile clean
    just -f off-chain/Justfile clean
    rm -f blueprint/plutus.json
    @echo '{{BOLD + GREEN}}✓ Clean complete{{NORMAL}}'
